# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-BigInt-FastCalc
version:      0.07
version_from: lib/Math/BigInt/FastCalc.pm
installdirs:  site
requires:
    Math::BigInt:                  1.72

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
