---
abstract: 'Math::BigInt::Calc with some XS for more speed'
author:
  - 'Original math code by Mark Biggar, rewritten by Tels L<http://bloodgate.com/>'
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BigInt-FastCalc
no_index:
  directory:
    - inc
    - t
requires:
  Math::BigInt: 1.90
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.22
