--- #YAML:1.0
name: Math-BigInt-FastCalc
version: 0.10
version_from: lib/Math/BigInt/FastCalc.pm
license: perl
distribution_type: module
generated_by: Math-BigInt-FastCalc version 0.10
installdirs: perl
requires:
  Math::BigInt: 1.76
